# Generated by Django 5.2 on 2025-04-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medication_patient_appointment_treatmentrecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='dispenselog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='dispenselog',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='dispenselog',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='treatmentmedication',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='treatmentmedication',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='treatmentmedication',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='treatmentrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='treatmentrecord',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='treatmentrecord',
            name='updated_by',
        ),
    ]
