# Generated by Django 5.2 on 2025-04-21 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointment_creator_alter_billing_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='core.patient', verbose_name='환자'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='treatment_record',
            field=models.OneToOneField(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billings', to='core.treatmentrecord', verbose_name='진료기록'),
        ),
        migrations.AlterField(
            model_name='dispenselog',
            name='medication',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='dispense_logs', to='core.medication', verbose_name='약품'),
        ),
        migrations.AlterField(
            model_name='dispenselog',
            name='treatment_medication',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='dispense_logs', to='core.treatmentmedication', verbose_name='처방약'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='medication',
            field=models.OneToOneField(db_index=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='inventory', serialize=False, to='core.medication', verbose_name='약품'),
        ),
        migrations.AlterField(
            model_name='treatmentmedication',
            name='medication',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_medications', to='core.medication', verbose_name='약품'),
        ),
        migrations.AlterField(
            model_name='treatmentmedication',
            name='treatment_record',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_medications', to='core.treatmentrecord', verbose_name='진료기록'),
        ),
        migrations.AlterField(
            model_name='treatmentrecord',
            name='appointment',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_records', to='core.appointment', verbose_name='예약'),
        ),
        migrations.AlterField(
            model_name='treatmentrecord',
            name='patient',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_records', to='core.patient', verbose_name='환자'),
        ),
    ]
