# Generated by Django 5.2 on 2025-04-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='bitrhday',
            new_name='birthday',
        ),
    ]
