# Generated by Django 5.2 on 2025-04-22 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_bitrhday_patient_birthday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_appointment_records', to=settings.AUTH_USER_MODEL, verbose_name='담당의사'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(help_text='거주지 주소 (도로명 주소 권장)', max_length=100, verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(help_text='환자의 생년월일 (YYYY-MM-DD)', verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], help_text='M: 남성, F: 여성, O: 기타 중 하나 선택', max_length=1, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(help_text='환자의 이름', max_length=20, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(help_text='휴대폰 번호 또는 유선전화 번호', max_length=20, verbose_name='전화번호'),
        ),
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
    ]
